version: '3.4'
services:
  db:
    image: ffjunior/mysql-backend-simple-test
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: Dockerfile      
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: backend-simple-test-db
    ports:
      - "3308:3306"
    networks:
      - cadastro-network
  backend-simple-test:
    image: ffjunior/backend-simple-test
    restart: always
    build: ./backend-simple-test
    working_dir: /backend-simple-test
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes:
      - ./backend-simple-test:/backend-simple-test
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - cadastro-network
networks:
    cadastro-network:
        driver: bridge